config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :operations do
    post 'calculate'
    get 'calculate', to: 'index'
  end

  root to: 'operations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_value, only: [:calculate,:index]

  def index
  end

  def calculate
    begin
      @value = eval(@value)
      flash[:notice] = "Cálculo efetuado com sucesso!"
    rescue Exception => exc
        @value = ""
        flash[:alert] = "Função inválida !"
    end
    render :index
  end

  def set_value
    if (params[:Input] == "" || params[:Input].nil?)
      @value="0"
    else
      @value = params[:Input]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><%= t('project_name') %></a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li>
                <%= link_to( t('logout'), destroy_user_session_path, method: :delete) %>
              </li>
            <% else %>
              <li>
              <%= link_to('Login', new_user_session_path)  %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/operations/_form.erb
<%= form_tag operations_calculate_path, :id => "form",:class => "Calc",:name => "Calc" do %>
<table class="table">
  <tbody>
    <tr>
      <th colspan="4">
        <%= text_field_tag :Input,(@value)  %>
      </th>
    </tr>
    <tr>
      <td> <button type="button" class="btn btn-primary" name="one" value="  1  " onClick="Calc.Input.value += '1'"> 1 </button>  </td>
      <td> <button type="button" class="btn btn-primary" name="one" value="  2  " onClick="Calc.Input.value += '2'"> 2 </button>  </td>
      <td> <button type="button" class="btn btn-primary" name="one" value="  3  " onClick="Calc.Input.value += '3'"> 3 </button>  </td>
      <td> <button type="button" class="btn btn-primary" name="one" value="  +  " onClick="Calc.Input.value += '+'"> + </button>  </td>
    </tr>
    <tr>
      <td> <button type="button" class="btn btn-primary" name="one" value="  4  " onClick="Calc.Input.value += '4'"> 4 </button>  </td>
      <td> <button type="button" class="btn btn-primary" name="one" value="  5  " onClick="Calc.Input.value += '5'"> 5 </button>  </td>
      <td> <button type="button" class="btn btn-primary" name="one" value="  6  " onClick="Calc.Input.value += '6'"> 6 </button>  </td>
      <td> <button type="button" class="btn btn-primary" name="one" value="  -  " onClick="Calc.Input.value += '-'"> - </button>  </td>
    </tr>
    <tr>
      <td> <button type="button" class="btn btn-primary" name="one" value="  7  " onClick="Calc.Input.value += '1'"> 1 </button>  </td>
      <td> <button type="button" class="btn btn-primary" name="one" value="  8  " onClick="Calc.Input.value += '2'"> 2 </button>  </td>
      <td> <button type="button" class="btn btn-primary" name="one" value="  9  " onClick="Calc.Input.value += '3'"> 3 </button>  </td>
      <td> <button type="button" class="btn btn-primary" name="one" value="  *  " onClick="Calc.Input.value += '*'"> x </button>  </td>
    </tr>
    <tr>
      <td> <button type="button" class="btn btn-primary" name="one" value="  c  " onClick="Calc.Input.value = '' "> c </button>  </td>
      <td> <button type="button" class="btn btn-primary" name="one" value="  0  " onClick="Calc.Input.value += '0'"> 0 </button>  </td>
      <td>
        <%= submit_tag('=', class: "btn btn-primary") %>
      </td>
      <td> <button type="button" class="btn btn-primary" name="one" value="  /  " onClick="Calc.Input.value += '/'"> / </button> </td>
    </tr>
  </tbody>
</table>
<% end %>

app/views/operations/index.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <%= render partial: "operations/form" %>
  </div>
</div>